name: Package Electron
on:
  workflow_run:
    workflows: ["Bump Version"]
    types: [completed]
jobs:
  release:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1

      - name: Read node from package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version

      - name: Show node version number
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo "Version is ${{ steps.package-node-version.outputs.version }}"
